# Generated by Django 3.1.7 on 2021-05-30 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boec_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('desc', models.CharField(blank=True, db_column='Desc', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('shipping_address', models.CharField(blank=True, db_column='ShippingAddress', max_length=255, null=True)),
                ('payment_type', models.CharField(blank=True, db_column='Payment_type', max_length=255, null=True)),
                ('create_at', models.DateTimeField(auto_now=True, db_column='create_at')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('desc', models.CharField(blank=True, db_column='Desc', max_length=255, null=True)),
                ('category', models.ForeignKey(db_column='CategoryId', on_delete=django.db.models.deletion.CASCADE, to='boec_core.category')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now=True, db_column='create_at')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=255, null=True)),
                ('desc', models.CharField(blank=True, db_column='Desc', max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(db_column='address', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(db_column='phone', default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(db_column='Price')),
                ('product', models.ForeignKey(db_column='ProductId', on_delete=django.db.models.deletion.CASCADE, to='boec_core.product')),
                ('vendor', models.ForeignKey(db_column='VendorId', on_delete=django.db.models.deletion.CASCADE, to='boec_core.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(db_column='Price')),
                ('order', models.ForeignKey(db_column='OrderId', on_delete=django.db.models.deletion.CASCADE, to='boec_core.order')),
                ('product', models.ForeignKey(db_column='VariantId', on_delete=django.db.models.deletion.CASCADE, to='boec_core.productvariant')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='sale',
            field=models.ForeignKey(db_column='SellerID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale', to=settings.AUTH_USER_MODEL),
        ),
    ]
