# Generated by Django 3.1.7 on 2021-05-31 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boec_core', '0002_auto_20210530_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_feature',
            field=models.BooleanField(db_column='is_feature', default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_selling',
            field=models.BooleanField(db_column='is_selling', default=False),
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0)),
                ('content', models.CharField(blank=True, db_column='Content', max_length=255, null=True)),
                ('create_at', models.DateTimeField(auto_now=True, db_column='create_at')),
                ('customer', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(db_column='VariantId', on_delete=django.db.models.deletion.CASCADE, to='boec_core.productvariant')),
            ],
        ),
    ]
