# Generated by Django 3.1.7 on 2021-05-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boec_core', '0003_auto_20210531_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='sale_off',
            field=models.FloatField(db_column='sale_off', default=0, null=True),
        ),
    ]
