# Generated by Django 3.1.7 on 2021-06-01 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boec_core', '0005_auto_20210531_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderShip',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('price', models.FloatField(db_column='Price')),
                ('estimated_arrival', models.DateTimeField(db_column='estimated_arrival', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField(choices=[(1, 'DANG_XU_LY'), (2, 'DA_TIEP_NHAN'), (3, 'DANG_LAY_HANG'), (4, 'DANG_GIAO_HANG'), (5, 'DA_GIAO'), (6, 'HUY')], default=1)),
                ('create_at', models.DateTimeField(auto_now=True, db_column='create_at')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingDepartment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('desc', models.CharField(blank=True, db_column='Desc', max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ShippingInfo',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'DANG_XU_LY'), (2, 'DA_TIEP_NHAN'), (3, 'DANG_LAY_HANG'), (4, 'DANG_GIAO_HANG'), (5, 'DA_GIAO'), (6, 'HUY')], default=1),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='order',
            field=models.ForeignKey(db_column='OrderId', on_delete=django.db.models.deletion.CASCADE, to='boec_core.order'),
        ),
        migrations.AddField(
            model_name='ordership',
            name='order',
            field=models.ForeignKey(db_column='OrderId', on_delete=django.db.models.deletion.CASCADE, to='boec_core.order'),
        ),
        migrations.AddField(
            model_name='ordership',
            name='ship',
            field=models.ForeignKey(db_column='ShipId', on_delete=django.db.models.deletion.CASCADE, to='boec_core.shippingdepartment'),
        ),
    ]
