# Generated by Django 3.1.7 on 2021-06-02 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boec_core', '0007_auto_20210602_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, db_column='note', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='recv_city',
            field=models.CharField(blank=True, db_column='rcv_city', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='recv_email',
            field=models.CharField(blank=True, db_column='rcv_email', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='recv_phone',
            field=models.CharField(blank=True, db_column='rcv_phone', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(db_column='email', default='', max_length=100),
        ),
    ]
